# Generated by Django 3.2.4 on 2021-06-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prifile',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': ('Профиль',), 'verbose_name_plural': 'Профили'},
        ),
    ]
